// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuveyService.Models;

namespace SuveyService.Migrations
{
    [DbContext(typeof(SuveyServiceContext))]
    [Migration("20191208200022_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuveyService.Models.Suvey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookingEXperince");

                    b.Property<int>("NumberOFKids");

                    b.Property<string>("OtherComments");

                    b.Property<int>("SatisfactionWitHStaff");

                    b.Property<int>("SatisfactionWithCleaning");

                    b.Property<int>("SatisfactionWithFood");

                    b.HasKey("ID");

                    b.ToTable("Suvey");
                });
#pragma warning restore 612, 618
        }
    }
}
